# Generated by Django 3.0.4 on 2020-03-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_id', models.CharField(max_length=20)),
                ('sentence', models.TextField()),
            ],
        ),
    ]
