# Generated by Django 3.0.4 on 2020-03-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='meaning',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
