# Generated by Django 3.0.4 on 2020-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence_learning', '0002_sentence_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='meaning',
            field=models.TextField(default='문장 뜻'),
        ),
    ]
