# Generated by Django 3.0.4 on 2020-03-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence_learning', '0003_auto_20200306_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='meaning',
        ),
    ]
